motion-primitives:
  - forward
  - 45-degree-left
  - 45-degree-right
  - forward-up
  - 45-degree-right-up
  - 45-degree-left-up
  - forward-down
  - 45-degree-right-down
  - 45-degree-left-down

motion-primitive-params:
  - forward: 5
  - 45-degree-left: 5
  - 45-degree-right: 5
  - forward-up: 5
  - 45-degree-right-up: 5
  - 45-degree-left-up: 5
  - forward-down: 5
  - 45-degree-right-down: 5
  - 45-degree-left-down: 5

